apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "astro-landing-strapi.fullname" . }}
  labels:
    {{- include "astro-landing-strapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "astro-landing-strapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "astro-landing-strapi.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "astro-landing-strapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.internalPort }}
              protocol: TCP
          volumeMounts:
          - mountPath: /data
            name: database
          envFrom:
          - configMapRef:
              name: sputnik-v2-configmap
          - configMapRef:
              name: astro-landing-strapi-configmap
          - configMapRef:
              name: {{ .Release.Name }}-version
          - secretRef:
              name: astro-landing-strapi-db-secret
          - secretRef:
              name: astro-landing-strapi-s3-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: {{ include "astro-landing-strapi.fullname" $ }}
