{{- if .Values.pvc.class }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "astro-landing-strapi.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.pvc.size }}"
  storageClassName: "{{ .Values.pvc.class }}"
  volumeMode: Filesystem
{{- end }}
