apiVersion: v1
kind: Service
metadata:
  name: {{ include "astro-landing-strapi.fullname" . }}
  labels:
    {{- include "astro-landing-strapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "astro-landing-strapi.selectorLabels" . | nindent 4 }}
