name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - name: load env
      run: |
          cat ".github/env.common" | grep -E -v '^\ *#' >>$GITHUB_ENV
          cat ".github/env.develop" | grep -E -v '^\ *#' >>$GITHUB_ENV

    - name: Build
      uses: ./.github/actions/build
